# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "imagick"
    filter_sets:
        small:
            quality: 90
            filters:
                relative_resize:
                    heighten: 720
                    # Will allow smaller images to take 800px of height,
                    # width will change accordingly since aspect ration is still valid.
                    allow_upscale: true
            post_processors:
                jpegoptim: { strip_all: true, max: 90, progressive: true }

        big:
            quality: 90
            filters:
                relative_resize:
                    heighten: 1080
                    # Will allow smaller images to take 800px of height,
                    # width will change accordingly since aspect ration is still valid.
                    allow_upscale: true
            post_processors:
                jpegoptim: { strip_all: true, max: 90, progressive: true }